display_errors=1
error_reporting=E_ALL

session.use_strict_mode=1
session.cookie_httponly=1
session.cookie_samesite=Lax

upload_max_filesize=20M
post_max_size=20M

date.timezone=Europe/Madrid

pdo_mysql.default_socket=